server:
  host: 127.0.0.1:8080
  clientTokenKey: "mall-token"
jwt:
  secret: "jwt-mall-key"
mysql:
  dsn: "golang_mall:password@tcp(localhost:3306)/golang_mall?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "localhost:6379"